### ISSUE TITLE
Example gff3 and bam file parsing works but strange behavior on gencode gff3

### ISSUE THREAD

**Issue by jelber2** [zaeleus/noodles-squab#1]
Hi,

Thanks for developing this cool tool. I came across perhaps an edge case that might be a difficult to debug with a gencode gff3 file. Unfortunately, I cannot share the BAM file, but what is strange is by accident, I got the command to work by using only the first few lines of the gff3

    $ wget http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M27/gencode.vM27.annotation.gff3.gz
    $ noodles-squab     --verbose     quantify     --annotations gencode.vM27.annotation.gff3.gz --output sample.counts.tsv Aligned.sortedByCoord.out.bam
    Oct 11 09:15:45.764  INFO noodles_squab: using 24 thread(s)
    Oct 11 09:15:45.767  INFO noodles_squab: reading features
    Error: invalid attributes: invalid entry: empty input

    $ noodles-squab     --verbose     quantify     --annotations <(zcat gencode.vM27.annotation.gff3.gz|head) --output sample.counts.tsv Aligned.sortedByCoord.out.bam
    Oct 11 09:16:19.173  INFO noodles_squab: using 24 thread(s)
    Oct 11 09:16:19.175  INFO noodles_squab: reading features
    Oct 11 09:16:19.182  INFO noodles_squab: read 1 unique features
    Oct 11 09:16:19.200  INFO noodles_squab::commands::quantify: detecting library type
    Oct 11 09:16:19.324  INFO noodles_squab::commands::quantify: library layout: paired end
    Oct 11 09:16:19.324  INFO noodles_squab::commands::quantify: strand specification: none (confidence: 0.00)
    Oct 11 09:16:19.324  INFO noodles_squab::commands::quantify: counting features
    Oct 11 09:16:19.909  INFO noodles_squab::commands::quantify: writing counts

    $ cat sample.counts.tsv
    ENSMUSG00000102693.2	0
    __no_feature	178883
    __ambiguous	0
    __too_low_aQual	0
    __not_aligned	0
    __alignment_not_unique	24272

I am not sure what line of the gff3 is the culprit

**Comment by zaeleus** [comment]
Hi, @jelber2! Thanks for reporting this. (squab is a testbed for [noodles-{bam,gff}](https://github.com/zaeleus/noodles); I didn't know anyone was using it!)

This is a rather interesting error because I typically use the human gene annotations from GENCODE for testing without issue. I suspect the mouse GFF3 file (`gencode.vM27.annotation.gff3.gz`) is not a valid GFF3.

The error is first thrown on line 219836:

```
chr2	HAVANA	transcript	122461146	122474717	.	+	.	ID=ENSMUST00000239507.1;Parent=ENSMUSG00000118663.1;gene_id=ENSMUSG00000118663.1;transcript_id=ENSMUST00000239507.1;gene_type=protein_coding;gene_name=Spata5l1;transcript_type=processed_transcript;transcript_name=RP23-101F14.5-002;level=2;
```

In GFF3, the semicolon (`;`) is used as the entry separator in the attributes column. Note that this particular record column ends with that separator. During parsing, the final entry ends up as an empty token, and thus, the error ("invalid entry: empty input").

There are only a handful of these, so this is likely an error by GENCODE.

```sh
$ zgrep --count ";$" gencode.vM27.annotation.gff3.gz
20
```

I'll contact the GENCODE help desk to first determine whether this is intended or not.

**Comment by zaeleus** [comment]
Just a heads up, the GFF3 files from GENCODE are now fixed (since ~October 14).
